version: '3.8'

services:
  nestjs-api:
    container_name: book-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3000
    env_file:
      - ./.env
